# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# added June 8th, 2017

language: R
dist: trusty
sudo: false
cache: packages
warnings_are_errors: false

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'
